import "../styles/globals.css";
import "../styles/home.module.css";
import "../styles/portfolio.module.css";
import type { AppProps } from "next/app";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Codersque</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;
