import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Codersque</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Typography color="primary" variant="h1">
        CODERSQUE
      </Typography>
    </>
  );
};

export default Home;
